trigger:
  branches:
    include:
      - main
  paths:
    exclude:
      - docs
      - licenses

pr: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: cpi-dev
  - group: cpi-neo

steps:
# https://docs.microsoft.com/azure/devops/pipelines/tasks/build/maven
- task: Maven@3
  displayName: 'Unit test'
  inputs:
    mavenOptions: '-Xmx3072m'
    jdkVersionOption: '1.8'
    goals: 'test'
- task: Maven@3
  displayName: 'Integration test on CF'
  inputs:
    mavenOptions: '-Xmx3072m'
    jdkVersionOption: '1.8'
    goals: 'clean verify'
    testResultsFiles: '**/failsafe-reports/TEST-*.xml'
    options: '-Dskip.unit.tests -Dit.test=io.github.engswee.flashpipe.cpi.api.*IT'
  env:
    HOST_TMN: $(dev-host-tmn)
    HOST_OAUTH: $(dev-oauth-host)
    OAUTH_CLIENTID: $(dev-client-id)
    OAUTH_CLIENTSECRET: $(dev-client-secret)
    BASIC_USERID: $(dev-user)
    BASIC_PASSWORD: $(dev-password)
- task: Maven@3
  displayName: 'Integration test on Neo - simulation'
  inputs:
    mavenOptions: '-Xmx3072m'
    jdkVersionOption: '1.8'
    goals: 'clean verify'
    testResultsFiles: '**/failsafe-reports/TEST-*.xml'
    options: '-Dskip.unit.tests -Dit.test=io.github.engswee.flashpipe.cpi.simulation.*IT'
  env:
    HOST_TMN: $(neo-host-tmn)
    BASIC_USERID: $(neo-user)
    BASIC_PASSWORD: $(neo-password)
# https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/docker
  # Lite version
- task: Docker@2
  inputs:
    containerRegistry: 'Docker Hub engswee'
    repository: 'engswee/flashpipe'
    command: 'buildAndPush'
    Dockerfile: 'src/main/docker/lite.Dockerfile'
    buildContext: '.'
    # FLASHPIPE_VERSION
    tags: |
      2.4.0-lite
      2.4.x-lite
      2.x.x-lite
# Full version with Maven
- task: Docker@2
  inputs:
    containerRegistry: 'Docker Hub engswee'
    repository: 'engswee/flashpipe'
    command: 'buildAndPush'
    Dockerfile: 'src/main/docker/Dockerfile'
    buildContext: '.'
    # FLASHPIPE_VERSION
    tags: |
      2.4.0
      2.4.x
      2.x.x